name: Deploy Serverless Container

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: cr.yandex/${{ secrets.YC_REGISTRY_ID }}
  IMAGE_REPO: pizza-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get IAM Token
        id: get-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build and push image
        run: |
          docker build -t $REGISTRY/$IMAGE_REPO:latest .
          docker push $REGISTRY/$IMAGE_REPO:latest
      
      - name: Deploy Serverless Container revision
        uses: yc-actions/yc-sls-container-deploy@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.FOLDER_ID }}
          container-name: pizza-backend
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-concurrency: 4
          revision-execution-timeout: 60
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/pizza-backend:latest
          revision-environment: |
            NODE_ENV=production
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            GITHUB_CLIENT_ID=${{ secrets.GHUB_CLIENT_ID }}
            GITHUB_CLIENT_SECRET=${{ secrets.GHUB_CLIENT_SECRET }}
            GITHUB_CALLBACK_URL=${{ secrets.GHUB_CALLBACK_URL }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
            JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
