name: Deploy Serverless Container

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: cr.yandex/${{ secrets.YC_REGISTRY_ID }}
  IMAGE_REPO: pizza-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Yandex IAM Token
        id: YC_TOKEN
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          ya-sa-id: ${{ secrets.YA_SA_ID }}

      - name: Authenticate to Yandex Cloud
        uses: yc-actions/authorize@v1
        with:
          yc-sa-id: ${{ secrets.YC_SA_ID }}
          yc-folder-id: ${{ secrets.FOLDER_ID }}

      - name: Build and push image
        run: |
          docker build -t $REGISTRY/$IMAGE_REPO:latest .
          docker push $REGISTRY/$IMAGE_REPO:latest

      - name: Deploy Serverless Container revision
        uses: yc-actions/yc-sls-container-deploy@v3
        with:
          yc-sa-id: ${{ secrets.YC_SA_ID }}
          folder-id: ${{ secrets.FOLDER_ID }}
          container-name: $IMAGE_REPO
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-concurrency: 4
          revision-execution-timeout: 60
          revision-image-url: $REGISTRY/$IMAGE_REPO:latest
